### ISSUE TITLE
Exception bug - Using Drain to pump to Advanced Generators Heat Exchanger [1.8.9]

### ISSUE THREAD

**Issue by ghost** [cyanobacterium/PowerAdvantageAPI#21]
https://github.com/cyanobacterium/PowerAdvantageAPI/issues/8

I saw that there was a similar error from above issue, but it was closed and wasn't sure if it was identical. It looks like it is to me, but I have no idea.

So I'm using the grain from Power Advantage and running a pipe to the [fluid intake valve](https://bdew.net/generators/heat-exchanger/) for the Heat Exchanger in [Advanced Generators](https://github.com/bdew/generators/releases). As soon as I connect the pipes, my frames start dropping and I notice the errors in the console.

Minecraft 1.8.9
Forge 11.15.1.1902
Power Advantage 1.5.5

[Latest Log](https://pastenib.com/v/rdwWHDXu2Wt7VevKgMaW)

[Second Try-Latest Log](https://pastenib.com/v/gaKCZDAuO82hlHd6LgYZ)

EDIT: Beautiful mods you have here btw.

**Comment by DrPlantabyte** [comment]
I honestly don't know how to fix Inventory Tweaks errors. It shouldn't be sorting the inventories of the Power Advantage pipes because their inventory size is 0. Does Inventory Tweaks have an option to not sort inventories with a size of 0?

**Comment by ghost** [comment]
Wait...It wasn't inventory Tweaks trying to do anything with the pipes is it?

Sorry about the vague description. I was talking more about this section:

`[19:30:47] [Server thread/ERROR]: A TileEntity type cyano.poweradvantage.machines.fluidmachines.modsupport.TerminalFluidPipeTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
    at cyano.poweradvantage.machines.fluidmachines.modsupport.TerminalFluidPipeTileEntity.getEnergy(TerminalFluidPipeTileEntity.java:82) ~[TerminalFluidPipeTileEntity.class:?]
    at cyano.poweradvantage.api.PoweredEntity.func_145841_b(PoweredEntity.java:163) ~[PoweredEntity.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:368) [anj.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:165) [anj.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:238) [ld.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:298) [ld.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:905) [le.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:366) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:137) [bpo.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]`

**Comment by DrPlantabyte** [comment]
I think I found the bug. I didn't increment the version number, so just re-download version 1.5.6

**Comment by ghost** [comment]
Perfect! Thank you very much!
